name: CloudnetPy-QC CI

on: [push]

jobs:
  build:

    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install libudunits2-dev
        pip install --upgrade pip
        pip install .[test]
    - name: Lint with pylint
      run: |
        pylint cloudnetpy_qc
    - name: Type check
      run: |
        mypy --ignore-missing-import cloudnetpy_qc/ tests/
    - name: Test with pytest-flakefinder
      run: |
        pytest --flake-finder tests/ --flake-runs=2
