name: CloudnetPy-QC CI

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libudunits2-dev
          version: 1.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install .[test]
      - name: Lint with pylint
        run: |
          pylint cloudnetpy_qc
      - name: Type check
        run: |
          mypy cloudnetpy_qc/ tests/
      - name: Test with pytest-flakefinder
        run: |
          pytest --flake-finder tests/ --flake-runs=2
